apiVersion: v1
kind: Service
metadata:
  name: result
  labels:
    app: result
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30100
    protocol: TCP
    name: http
  selector:
    app: result
